import CardPhoto1 from "../public/images/image 12.png";
import CardPhoto2 from "../public/images/wedding-photography 1.png";
import CardPhoto3 from "../public/images/mountain-bike 1.png";
// eslint-disable-next-line no-undef
export default [
  {
    id: 1,
    img: CardPhoto1,
    rating: "5.0",
    reviewCount: 6,
    country: "Usa",
    title: "Life lessons with Katie Zaferes",
    price: 136,
  },
  {
    id: 2,
    img: CardPhoto2,
    rating: "5.0",
    reviewCount: 6,
    country: "Usa",
    title: "Learn wedding photography",
    price: 136,
  },
  {
    id: 3,
    img: CardPhoto3,
    rating: "5.0",
    reviewCount: 6,
    country: "Usa",
    title: "Group Mountain Biking",
    price: 136,
  },
  {
    id: 4,
    img: CardPhoto3,
    rating: "5.0",
    reviewCount: 6,
    country: "Usa",
    title: "Group Mountain Biking",
    price: 136,
  },
  {
    id: 5,
    img: CardPhoto3,
    rating: "5.0",
    reviewCount: 6,
    country: "Usa",
    title: "Group Mountain Biking",
    price: 136,
  },
  {
    id: 6,
    img: CardPhoto3,
    rating: "5.0",
    reviewCount: 6,
    country: "Usa",
    title: "Group Mountain Biking",
    price: 136,
  },
  {
    id: 7,
    img: CardPhoto3,
    rating: "5.0",
    reviewCount: 6,
    country: "Usa",
    title: "Group Mountain Biking",
    price: 136,
  },
  {
    id: 8,
    img: CardPhoto3,
    rating: "5.0",
    reviewCount: 6,
    country: "Usa",
    title: "Group Mountain Biking",
    price: 136,
  },
  {
    id: 9,
    img: CardPhoto3,
    rating: "5.0",
    reviewCount: 6,
    country: "Usa",
    title: "Group Mountain Biking",
    price: 136,
  },
  {
    id: 10,
    img: CardPhoto3,
    rating: "5.0",
    reviewCount: 6,
    country: "Usa",
    title: "Group Mountain Biking",
    price: 136,
  },
  {
    id: 11,
    img: CardPhoto3,
    rating: "5.0",
    reviewCount: 6,
    country: "Usa",
    title: "Group Mountain Biking",
    price: 136,
  },
];
